"""
Project Management System for HTR Analysis Tool v2
Handles project creation, loading, and organization.
"""
import os
import json
import shutil
from datetime import datetime
from pathlib import Path
from PySide6.QtCore import QObject, Signal


class ProjectManager(QObject):
    """Manages HTR analysis projects with unified folder structure."""
    
    project_loaded = Signal(str)  # Emitted when project loaded
    project_created = Signal(str)  # Emitted when project created
    
    def __init__(self):
        super().__init__()
        self.current_project_path = None
        self.current_project_config = None
        
    def create_project(self, project_path, project_name, workflow_type="batch"):
        """Create a new HTR analysis project."""
        try:
            project_folder = os.path.join(project_path, project_name)
            
            # Create main project folder
            os.makedirs(project_folder, exist_ok=True)
            
            # Create project structure
            folders = [
                "input",           # H5 files and videos
                "features",        # Generated features (unlabeled)
                "training",        # Labeled training data
                "predictions",     # HTR predictions
                "reports",         # Final reports
                "models",          # Trained models
                "parameters"       # Parameter configurations
            ]
            
            for folder in folders:
                os.makedirs(os.path.join(project_folder, folder), exist_ok=True)
            
            # Create project config
            config = {
                "project_name": project_name,
                "created_date": datetime.now().isoformat(),
                "last_modified": datetime.now().isoformat(),
                "workflow_type": workflow_type,
                "version": "2.0",
                "paths": {
                    "input": "./input",
                    "features": "./features",
                    "training": "./training",
                    "predictions": "./predictions",
                    "reports": "./reports",
                    "models": "./models",
                    "parameters": "./parameters"
                },
                "settings": {
                    "current_parameters": None,
                    "current_model": None,
                    "default_fps": 120
                },
                "workflow_status": {
                    "parameters_tuned": False,
                    "model_trained": False,
                    "features_extracted": False,
                    "predictions_made": False,
                    "report_generated": False
                },
                "file_counts": {
                    "h5_files": 0,
                    "video_files": 0,
                    "feature_files": 0,
                    "prediction_files": 0,
                    "model_files": 0
                },
                "training_files": [],  # List of CSV files in training folder
                "training_stats": {
                    "total_labeled_events": 0,
                    "htr_count": 0,
                    "non_htr_count": 0
                }
            }
            
            # Save config file
            config_path = os.path.join(project_folder, "project_config.json")
            with open(config_path, 'w') as f:
                json.dump(config, f, indent=2)
            
            # Create README
            readme_content = f"""# HTR Analysis Project: {project_name}

Created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Workflow Type: {workflow_type.title()}

## Project Structure:
- input/         - Place your H5 files and videos here
- features/      - Generated feature files (.csv)  
- predictions/   - HTR prediction results (.csv)
- reports/       - Final analysis reports (.xlsx)
- models/        - Trained ML models (.joblib)
- parameters/    - Parameter configuration files (.json)

## Workflow:
1. Add your data files to the input/ folder
2. Use the HTR Analysis Tool to process your data
3. Results will be organized automatically in the appropriate folders

Generated by HTR Analysis Tool v2
"""
            
            readme_path = os.path.join(project_folder, "README.md")
            with open(readme_path, 'w') as f:
                f.write(readme_content)
            
            # Set as current project
            self.current_project_path = project_folder
            self.current_project_config = config
            
            self.project_created.emit(project_folder)
            return True, project_folder
            
        except Exception as e:
            return False, f"Failed to create project: {str(e)}"
    
    def load_project(self, project_folder):
        """Load an existing HTR analysis project."""
        try:
            config_path = os.path.join(project_folder, "project_config.json")
            
            if not os.path.exists(config_path):
                return False, "Not a valid HTR project (missing project_config.json)"
            
            # Load config
            with open(config_path, 'r') as f:
                config = json.load(f)
            
            # Update last modified
            config["last_modified"] = datetime.now().isoformat()
            
            # Validate project structure
            required_folders = ["input", "features", "training", "predictions", "reports", "models", "parameters"]
            for folder in required_folders:
                folder_path = os.path.join(project_folder, folder)
                if not os.path.exists(folder_path):
                    os.makedirs(folder_path, exist_ok=True)

            # Ensure training_files and training_stats exist (for backward compatibility)
            if "training_files" not in config:
                config["training_files"] = []
            if "training_stats" not in config:
                config["training_stats"] = {
                    "total_labeled_events": 0,
                    "htr_count": 0,
                    "non_htr_count": 0
                }
            
            # Update file counts
            config["file_counts"] = self._count_project_files(project_folder)
            
            # Save updated config
            with open(config_path, 'w') as f:
                json.dump(config, f, indent=2)
            
            # Set as current project
            self.current_project_path = project_folder
            self.current_project_config = config
            
            self.project_loaded.emit(project_folder)
            return True, project_folder
            
        except Exception as e:
            return False, f"Failed to load project: {str(e)}"
    
    def _count_project_files(self, project_folder):
        """Count files in project folders."""
        import glob
        
        counts = {}
        
        # Count H5 files
        h5_pattern = os.path.join(project_folder, "input", "**", "*.h5")
        counts["h5_files"] = len(glob.glob(h5_pattern, recursive=True))
        
        # Count video files
        video_patterns = [
            os.path.join(project_folder, "input", "**", "*.mp4"),
            os.path.join(project_folder, "input", "**", "*.avi")
        ]
        counts["video_files"] = sum(len(glob.glob(p, recursive=True)) for p in video_patterns)
        
        # Count feature files
        feature_pattern = os.path.join(project_folder, "features", "*.csv")
        counts["feature_files"] = len(glob.glob(feature_pattern))
        
        # Count prediction files
        prediction_pattern = os.path.join(project_folder, "predictions", "*.csv")
        counts["prediction_files"] = len(glob.glob(prediction_pattern))
        
        # Count model files
        model_pattern = os.path.join(project_folder, "models", "*.joblib")
        counts["model_files"] = len(glob.glob(model_pattern))
        
        return counts
    
    def get_current_project(self):
        """Get current project path and config."""
        return self.current_project_path, self.current_project_config
    
    def update_workflow_status(self, step, completed=True):
        """Update workflow status in project config."""
        if not self.current_project_config:
            return False
            
        self.current_project_config["workflow_status"][step] = completed
        self.current_project_config["last_modified"] = datetime.now().isoformat()
        
        # Save updated config
        if self.current_project_path:
            config_path = os.path.join(self.current_project_path, "project_config.json")
            with open(config_path, 'w') as f:
                json.dump(self.current_project_config, f, indent=2)
        
        return True

    def add_training_file(self, csv_filename, htr_count, non_htr_count):
        """
        Track a file that was moved to training folder and update training stats.

        Args:
            csv_filename: Name of the CSV file (just filename, not full path)
            htr_count: Number of HTR events (label = 1) in the file
            non_htr_count: Number of non-HTR events (label = 0) in the file
        """
        if not self.current_project_config:
            return False

        # Add to training files list if not already present
        if csv_filename not in self.current_project_config["training_files"]:
            self.current_project_config["training_files"].append(csv_filename)

        # Update training stats
        stats = self.current_project_config["training_stats"]
        stats["htr_count"] += htr_count
        stats["non_htr_count"] += non_htr_count
        stats["total_labeled_events"] = stats["htr_count"] + stats["non_htr_count"]

        # Update last modified
        self.current_project_config["last_modified"] = datetime.now().isoformat()

        # Save updated config
        if self.current_project_path:
            config_path = os.path.join(self.current_project_path, "project_config.json")
            with open(config_path, 'w') as f:
                json.dump(self.current_project_config, f, indent=2)

        return True

    def get_project_summary(self):
        """Get a summary of the current project status."""
        if not self.current_project_config:
            return None
            
        config = self.current_project_config
        file_counts = config.get("file_counts", {})
        workflow_status = config.get("workflow_status", {})
        
        summary = {
            "name": config.get("project_name", "Unknown"),
            "created": config.get("created_date", "Unknown"),
            "last_modified": config.get("last_modified", "Unknown"),
            "workflow_type": config.get("workflow_type", "Unknown"),
            "files": file_counts,
            "status": workflow_status,
            "ready_for_batch": (
                file_counts.get("h5_files", 0) > 0 and
                file_counts.get("model_files", 0) > 0
            ),
            "has_parameters": config.get("settings", {}).get("current_parameters") is not None
        }
        
        return summary